# Generated by Django 4.1.3 on 2022-12-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.CharField(max_length=25)),
                ('service_title', models.CharField(max_length=25)),
                ('service_des', models.TextField()),
            ],
        ),
    ]
